import { HangerData, SizeCategories, SizeMappings } from "./types";

export const SizeCategoriesOrdering: Record<
  SizeCategories | "Kids-(2A-8A)" | "Big-(10A-12A)",
  number
> = {
  Newborn: 1,
  Infant: 2,
  "Toddler-(2T-4T)": 3,
  "Kids-(4-6X)": 4,
  "Kids-(4-7X)": 5,
  "Big-(7-16)": 6,
  "Big-(8-20)": 7,
  "Kids-(2A-8A)": 8,
  "Big-(10A-12A)": 9,
};

export const COUNTRY_MAPPING: Record<string, string> = {
  "A109M-AC": "USA-Stock",
  "A109M-AD": "USA-Stock",
  "A109M-AH": "USA-Stock",
  "A109M-AM": "USA-Stock",
  "A109M-AN": "USA-Stock",
  "A311M-X0": "Global-India",
  "A313M-QO": "Global-Dubai",
  "A746M-AL": "Global-Israel",
  "C104M-G0": "Global-Thailand",
  "C104M-G8": "Global-Thailand",
  "C104M-G9": "Global-Thailand",
  "C104M-H0": "Global-Thailand",
  "D528M-DS": "USA-Stock",
  "D552M-DL": "USA-Stock",
  "H040M-": "USA-Stock",
  "H040M-EC": "USA-Stock",
  "H040M-ED": "USA-Stock",
  "H040M-EE": "USA-Stock",
  "H040M-EJ": "USA-Stock",
  "H040M-EM": "USA-Stock",
  "H040M-EN": "USA-Stock",
  "H040M-IP": "USA-Stock",
  "H040M-NH": "USA-Stock",
  "H040M-P2": "USA-Stock",
  "H040M-WH": "USA-Stock",
  "H040M-**": "USA-Stock",
  "H494M-L5": "Global-EUROPE",
  "H494M-LQ": "Global-EUROPE",
  "H494M-LR": "Global-EUROPE",
  "H494M-LV": "Global-EUROPE",
  "H494M-LW": "Global-EUROPE",
  "H494M-LY": "Global-EUROPE",
  "H494M-LZ": "Global-EUROPE",
  "H718M-KL": "Global-Korea",
  "H718M-KM": "Global-Korea",
  "H718M-KS": "Global-Korea",
  "H718M-KX": "Global-Korea",
  "I201M-KO": "Global-Mexico",
  "I201M-MH": "Global-Mexico",
  "I201M-MK": "Global-Mexico",
  "I201M-MO": "Global-Mexico",
  "I201M-MV": "Global-Mexico",
  "I644M-IA": "Global-Panama",
  "I644M-NL": "Global-Panama",
  "I867M-XL": "Global-Chile",
  "I952M-O9": "Global-Peru",
  "J121M-JC": "USA-Stock",
  "K812M-KO": "USA-Stock",
  "K816M-1Z": "USA-Stock",
  "K816M-2Z": "USA-Stock",
  "K816M-3Z": "USA-Stock",
  "K816M-4Z": "USA-Stock",
  "K816M-EK": "USA-Stock",
  "K816M-H6": "USA-Stock",
  "K816M-Z5": "USA-Stock",
  "K816M-Z7": "USA-Stock",
  "L004M-2X": "Costco Australia",
  "S068M-EY": "USA-SAM'S",
  "S068M-EZ": "USA-SAM'S",
  "S068M-SM": "USA-SAM'S",
  "S068M-SQ": "USA-SAM'S",
  "S068M-SU": "USA-SAM'S",
  "S960M-F5": "Global-Malaysia",
  "S974M-SY": "Global-South Africa",
  "T059M-TZ": "USA-Target",
  "T082M-DE": "USA-Target",
  "T082M-DF": "USA-Target",
  "T082M-DH": "USA-Target",
  "T082M-DM": "USA-Target",
  "T082M-EI": "USA-Target",
  "T082M-EL": "USA-Target",
  "T082M-EO": "USA-Target",
  "T082M-FO": "USA-Target",
  "T082M-GA": "USA-Target",
  "T082M-GC": "USA-Target",
  "T082M-GD": "USA-Target",
  "T082M-GE": "USA-Target",
  "T082M-GF": "USA-Target",
  "W098M-0W": "USA-WALMART",
  "W098M-W1": "USA-WALMART",
  "W098M-W2": "USA-WALMART",
  "W098M-W3": "USA-WALMART",
  "W098M-WM": "USA-WALMART",
  "W098M-WQ": "USA-WALMART",
  "W098M-WR": "USA-WALMART",
  "W113M-HA": "USA-WALMART",
  "W113M-HC": "USA-WALMART",
  "W113M-HD": "USA-WALMART",
  "W113M-HE": "USA-WALMART",
  "W113M-HF": "USA-WALMART",
  "W113M-HH": "USA-WALMART",
  "W113M-HI": "USA-WALMART",
  "W113M-HJ": "USA-WALMART",
  "W113M-HK": "USA-WALMART",
  "W113M-HL": "USA-WALMART",
  "W113M-HN": "USA-WALMART",
  "W113M-HO": "USA-WALMART",
  "W113M-HP": "USA-WALMART",
  "W113M-HR": "USA-WALMART",
  "W847M-WO": "USA-WALMART",
  "W846M-CT": "CANADA-WALMART",
  "W846M-CN": "Global-Canada STOCK",
  "W846M-FZ": "Global-CANADA FGL SPORTS",
  "W846M-WN": "Global-CANADA WINNERS",
  "Z090M-SV": "Global-Panama ZafariI",
};

export const SEASON: Record<string, string> = {
  s: "Spring",
  m: "Summer",
  f: "Fall",
  h: "Holiday",
};

export const SEASON_CODE: Record<string, number> = { S: 1, M: 2, F: 3, H: 4 };

export const EXCEL_COLUMN_HEADERS = [
  "Division",
  "Season",
  "Year",
  "Ref#",
  "Style",
  "Style Name",
  "Color",
  "Label",
  "Label Name",
  "Account",
  "Fashion Color",
  "Cost ($)",
  "Extension ($)",
  "PO#",
  "Terms Code",
  "DF/PO Placed",
  "Status",
  "Original ETD",
  "Ship Date",
  "Ship Month",
  "Days Late",
  "xFTY Date",
  "ETA Date",
  "Due Date",
  "PO Qty",
  "AIR/BOAT",
  "Freight Type",
  "Parent Vendor",
  "Contractor",
  "MSRP($)",
  "Brand(G1)",
  "Product(G2)",
  "Product Description",
  "SubBrand(G3)",
  "Size(G4)",
  "Size Range",
  "Size Configuration",
  "Pack Ratio",
  "Master Box Quantity",
  "Number Of Bundles",
  "Pieces In Bundle",
  "Hang/Flat",
  "Fashion Correctable Status",
  "Agent",
  "Country",
  "Full Year",
  "Size Group",
  "Hanger Group",
  "Season Code",
  "ACC ShipDate",
  "Zode Code",
  "Gander",
  "LP",
  "Sum Ratio",
  "individual Polybag",
  "master Polybag",
  "Individual Polybag Quantity",
  "Master Polybag Quantity",
  "color Code",
  "RefCode",
  "Des Country",
  "2T",
  "3T",
  "4T",
  "4",
  "5",
  "6",
  "7",
  "6X",
  "7X",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "4/5",
  "6/7",
  "8",
  "10/12",
  "14/16",
  "18",
  "2A",
  "3A",
  "4A",
  "5A",
  "6A",
  "8A",
  "10A",
  "12A",
  "14A",
  "16A",
];

export const EXCEL_ROW_HEADERS = [
  "Division",
  "Season",
  "Year",
  "Ref#",
  "Style",
  "Style Name",
  "Color",
  "Label",
  "Label Name",
  "Account",
  "Fashion Color",
  "Cost ($)",
  "Extension ($)",
  "PO#",
  "Terms Code",
  "DF/PO Placed",
  "Status",
  "Original ETD",
  "Ship Date",
  "Ship Month",
  "Days Late",
  "xFTY Date",
  "ETA Date",
  "Due Date",
  "PO Qty",
  "AIR/BOAT",
  "Freight Type",
  "Parent Vendor",
  "Contractor",
  "MSRP($)",
  "Brand(G1)",
  "Product(G2)",
  "Product Description",
  "SubBrand(G3)",
  "Size(G4)",
  "Size Range",
  "Size Configuration",
  "Pack Ratio",
  "Master Box Quantity",
  "Number Of Bundles",
  "Pieces In Bundle",
  "Hang/Flat",
  "Fashion Correctable Status",
  "Agent",
  "Country",
  "Full Year",
  "Hanger Code Top",
  "Hanger Code Button",
  "Season Code",
  "Gander",
  "LP",
  "ACC ShipDate",
  "Sum Ratio",
  "individual Polybag",
  "master Polybag",
  "color Code",
  "RefCode",
  "Des Country",
  "Zode Code",
  "Size Group Ordering",
  "Size Group",
  "Ordering Number",
  "By Size",
  "REF-C-S-D",
  "Final QTY",
];

export const LABEL_ZODE_MAP: Record<string, string> = {
  "NO HANGER": "US",
  "WITH HANGER": "US",
  "HADDAD - GLOBAL HOLD": "US",
  KOHLS: "US",
  "KOHLS.COM": "US",
  "KOHLS.COM - ALTERNATE": "US",
  "INDIVIDUAL POLYBAG": "US",
  ACADEMY: "AC",
  "WALMART STORES": "US",
  "WALMART STORES - ALTERNATE": "US",
  WALMART: "US",
  "WALMART - ALTERNATE": "US",
  "CANADA WORLD FAMOUS": "US",
  "TARGET.COM - ALTERNATE": "TA",
  "TARGET - ASSORTMENT": "TA",
  "ALTERNATE PACK": "US",
  "JC PENNEY": "US",
  "HBE EUROPE LEVIS": "EU",
  "INNOVA SPORT MEXICO": "MX",
  "INTERNATIONAL APPAREL CORP": "PA",
  "CENTRAL DEPARTMENT STORE LTD": "TH",
  "CHILE IAC": "CH",
  "AL-SRAD": "AS",
  DUBAI: "DU",
  "ZAFARI PANAMA": "PZ",
  "KOREA ALT PACKING": "KO",
  SKYE: "SA",
  "INDIA APPAREL GROUP": "IN",
  "CANADA - WINNERS": "CA",
  "PERU IAC": "PE",
  "CANADA - STOCK": "CA",
  "STREAM MALAYSIA": "ML",
  "HADDAD CANADA": "US-CA",
  "CANADA - WALMART STORE": "CA",
  ECOM: "Fake",
  "ECOM - ALT": "Fake",
};

export const POLY_BAG: Record<
  string,
  { individual: boolean; master: boolean }
> = {
  "AL-SRAD": { individual: true, master: true },
  "CENTRAL DEPARTMENT STORE LTD": { individual: true, master: false },
  "CHILE IAC": { individual: false, master: true },
  DUBAI: { individual: true, master: false },
  "INDIVIDUAL POLYBAG": { individual: true, master: false },
  "INNOVA SPORT MEXICO": { individual: true, master: true },
  "INTERNATIONAL APPAREL CORP": { individual: false, master: true },
  KOHLS: { individual: false, master: true },
  "KOHLS.COM": { individual: true, master: false },
  "KOHLS.COM - ALTERNATE": { individual: true, master: false },
  "KOREA ALT PACKING": { individual: true, master: false },
  "PERU IAC": { individual: false, master: true },
  SKYE: { individual: true, master: true },
  "STREAM MALAYSIA": { individual: true, master: true },
  WALMART: { individual: true, master: false },
  "WALMART - ALTERNATE": { individual: true, master: false },
  "ZAFARI PANAMA": { individual: true, master: true },
  "JC PENNEY": { individual: false, master: true },
  "DICK'S SPORTING GOODS": { individual: false, master: true },
  DEFAULT: { individual: false, master: false },
};

export const HANGER_DATA: { [account: string]: HangerData } = {
  H040M: {
    Newborn: { top: "495", bottom: "6108" },
    Infant: { top: "496", bottom: "6108" },
    "Toddler-(2T-4T)": { top: "496", bottom: "6108" },
    "Kids-(4-6X)": { top: "472", bottom: "6110" },
    "Kids-(4-7X)": { top: "472", bottom: "6110" },
    "Big-(7-16)": { top: "485B", bottom: "6012B" },
    "Big-(8-20)": { top: "485B", bottom: "6012B" },
  },
  K812M: {
    Newborn: { top: "496", bottom: "6108" },
    Infant: { top: "496", bottom: "6108" },
    "Toddler-(2T-4T)": { top: "496", bottom: "6108" },
    "Kids-(4-6X)": { top: "472", bottom: "6110" },
    "Kids-(4-7X)": { top: "472", bottom: "6110" },
    "Big-(7-16)": { top: "485B", bottom: "6012B" },
    "Big-(8-20)": { top: "485B", bottom: "6012B" },
  },
  A109M: {
    Newborn: { top: "497B", bottom: "6008B" },
    Infant: { top: "498B", bottom: "6008B" },
    "Toddler-(2T-4T)": { top: "498B", bottom: "6008B" },
    "Kids-(4-6X)": { top: "485B", bottom: "6010B" },
    "Kids-(4-7X)": { top: "485B", bottom: "6010B" },
    "Big-(7-16)": { top: "485B", bottom: "6010B" },
    "Big-(8-20)": { top: "485B", bottom: "6010B" },
  },
  W113M: {
    Newborn: { top: "WT-10", bottom: "WB6" },
    Infant: { top: "WT-10", bottom: "WB6" },
    "Toddler-(2T-4T)": { top: "WT-12", bottom: "496" },
    "Kids-(4-6X)": { top: "WT-12", bottom: "WB8" },
    "Kids-(4-7X)": { top: "WT-12", bottom: "WB8" },
    "Big-(7-16)": { top: "WT-15", bottom: "WB10" },
    "Big-(8-20)": { top: "WT-15", bottom: "WB10" },
  },
  W847M: {
    Newborn: { top: "495", bottom: "6108" },
    Infant: { top: "496", bottom: "6108" },
    "Toddler-(2T-4T)": { top: "496", bottom: "6108" },
    "Kids-(4-6X)": { top: "472", bottom: "6110" },
    "Kids-(4-7X)": { top: "472", bottom: "6110" },
    "Big-(7-16)": { top: "485B", bottom: "6012B" },
    "Big-(8-20)": { top: "485B", bottom: "6012B" },
  },
  T082M: {
    Newborn: { top: "T10BN", bottom: "B8MC" },
    Infant: { top: "T10BN", bottom: "B8MC" },
    "Toddler-(2T-4T)": { top: "T10BN", bottom: "B8MC" },
    "Kids-(4-6X)": { top: "T12BN", bottom: "B10MC" },
    "Kids-(4-7X)": { top: "T12BN", bottom: "B10MC" },
    "Big-(7-16)": { top: "T15BN", bottom: "B12C" },
    "Big-(8-20)": { top: "T15BN", bottom: "B12C" },
  },
  W846M: {
    Newborn: { top: "495", bottom: "6108" },
    Infant: { top: "496", bottom: "6108" },
    "Toddler-(2T-4T)": { top: "496", bottom: "6108" },
    "Kids-(4-6X)": { top: "472", bottom: "6110" },
    "Kids-(4-7X)": { top: "472", bottom: "6110" },
    "Big-(7-16)": { top: "467", bottom: "6112" },
    "Big-(8-20)": { top: "467", bottom: "6112" },
  },
  S960M: {
    Newborn: { top: "495", bottom: "6108" },
    Infant: { top: "496", bottom: "6108" },
    "Toddler-(2T-4T)": { top: "496", bottom: "6108" },
    "Kids-(4-6X)": { top: "472", bottom: "6110" },
    "Kids-(4-7X)": { top: "472", bottom: "6110" },
    "Big-(7-16)": { top: "472", bottom: "6112" },
    "Big-(8-20)": { top: "467", bottom: "6112" },
  },
  T059M: {} as HangerData,
};
HANGER_DATA["T059M"] = HANGER_DATA["T082M"]!;

export const SIZE_GROUP: SizeMappings = {
  US: {
    "2T": { order: 1, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "3T": { order: 2, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4T": { order: 3, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4": { order: 4, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "5": { order: 5, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6": { order: 6, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "7": { order: 7, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6X": { order: 8, boys: "", girls: "Kids-(4-6X)" },
    "7X": { order: 9, boys: "Kids-(4-7X)", girls: "" },
    "4/5": { order: 10, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6/7": { order: 11, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "8": { order: 12, boys: "Big-(8-20)", girls: "" },
    "10/12": { order: 13, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "14/16": { order: 14, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "18": { order: 15, boys: "Big-(8-20)", girls: "" },
    XS: { order: 16, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    S: { order: 17, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    M: { order: 18, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    L: { order: 19, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    XL: { order: 20, boys: "Big-(8-20)", girls: "Big-(7-16)" },
  },
  target: {
    "2T": { order: 1, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "3T": { order: 2, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4T": { order: 3, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4": { order: 4, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "5": { order: 5, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6": { order: 6, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "7": { order: 7, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6X": { order: 8, boys: "", girls: "Kids-(4-6X)" },
    "7X": { order: 9, boys: "Kids-(4-7X)", girls: "" },
    XS: { order: 10, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "4/5": { order: 11, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6/7": { order: 12, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "8": { order: 13, boys: "Big-(8-20)", girls: "" },
    "10/12": { order: 14, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "14/16": { order: 15, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "18": { order: 16, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    S: { order: 17, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    M: { order: 18, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    L: { order: 19, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    XL: { order: 20, boys: "Big-(8-20)", girls: "Big-(7-16)" },
  },
  walmart: {
    "2T": { order: 1, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "3T": { order: 2, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4T": { order: 3, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4": { order: 4, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "5": { order: 5, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6": { order: 6, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "7": { order: 7, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6X": { order: 8, boys: "", girls: "Kids-(4-6X)" },
    "7X": { order: 9, boys: "Kids-(4-7X)", girls: "" },
    XS: { order: 10, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    S: { order: 11, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "4/5": { order: 12, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6/7": { order: 13, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "8": { order: 14, boys: "Big-(8-20)", girls: "" },
    "10/12": { order: 15, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "14/16": { order: 16, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "18": { order: 17, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    M: { order: 18, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    L: { order: 19, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    XL: { order: 20, boys: "Big-(8-20)", girls: "Big-(7-16)" },
  },
  EU: {
    "2A": { order: 1, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "3A": { order: 2, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "4A": { order: 3, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "5A": { order: 4, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "6A": { order: 5, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "8A": { order: 6, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "10A": { order: 7, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
    "12A": { order: 8, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
    "14A": { order: 9, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
    "16A": { order: 10, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
  },
  default: {
    "3M": { order: 1, boys: "Newborn", girls: "Newborn" },
    "6M": { order: 2, boys: "Newborn", girls: "Newborn" },
    "9M": { order: 3, boys: "Newborn", girls: "Newborn" },
    "12M": { order: 4, boys: "Infant", girls: "Infant" },
    "18M": { order: 5, boys: "Infant", girls: "Infant" },
    "24M": { order: 6, boys: "Infant", girls: "Infant" },
    "36M": { order: 7, boys: "Infant", girls: "Infant" },
    "2T": { order: 9, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "3T": { order: 10, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4T": { order: 11, boys: "Toddler-(2T-4T)", girls: "Toddler-(2T-4T)" },
    "4": { order: 12, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "5": { order: 13, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6": { order: 14, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6X": { order: 15, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "7": { order: 16, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "7X": { order: 17, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "4/5": { order: 18, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "5/6": { order: 19, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6/6X": { order: 20, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "6/7": { order: 21, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    "7/8": { order: 22, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "8": { order: 23, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "10/12": { order: 24, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "14/16": { order: 25, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "18": { order: 26, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "18/20": { order: 27, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    XS: { order: 28, boys: "Kids-(4-7X)", girls: "Kids-(4-6X)" },
    S: { order: 29, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    M: { order: 30, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    L: { order: 31, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    XL: { order: 32, boys: "Big-(8-20)", girls: "Big-(7-16)" },
    "2A": { order: 33, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "3A": { order: 34, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "4A": { order: 34, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "5A": { order: 35, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "6A": { order: 36, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "8A": { order: 37, boys: "Kids-(2A-8A)", girls: "Kids-(2A-8A)" },
    "10A": { order: 38, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
    "12A": { order: 39, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
    "14A": { order: 40, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
    "16A": { order: 41, boys: "Big-(10A-12A)", girls: "Big-(10A-12A)" },
  },
};
