export const SIZE_ORDER: Record<string, number> = {
  "3M": 1,
  "6M": 2,
  "9M": 3,
  "12M": 4,
  "18M": 5,
  "24M": 6,
  "36M": 7,
  "2T": 9,
  "3T": 10,
  "4T": 11,
  4: 12,
  5: 13,
  6: 14,
  "6X": 15,
  7: 16,
  "7X": 17,
  "4/5": 18,
  "5/6": 19,
  "6/6X": 20,
  "6/7": 21,
  "7/8": 22,
  8: 23,
  "10/12": 24,
  "14/16": 25,
  18: 26,
  "18/20": 27,
  XS: 28,
  S: 29,
  M: 30,
  L: 31,
  XL: 32,
  "2A": 33,
  "3A": 34,
  "4A": 35,
  "5A": 36,
  "6A": 37,
  "8A": 38,
  "10A": 39,
  "12A": 40,
  "14A": 41,
  "16A": 42,
};

export const COUNTRY_MAPPING: Record<string, string> = {
  "A109M-AC": "USA-Stock",
  "A109M-AD": "USA-Stock",
  "A109M-AH": "USA-Stock",
  "A109M-AM": "USA-Stock",
  "A109M-AN": "USA-Stock",
  "A311M-X0": "Global-India",
  "A313M-QO": "Global-Dubai",
  "A746M-AL": "Global-Israel",
  "C104M-G0": "Global-Thailand",
  "C104M-G8": "Global-Thailand",
  "C104M-G9": "Global-Thailand",
  "C104M-H0": "Global-Thailand",
  "D528M-DS": "USA-Stock",
  "D552M-DL": "USA-Stock",
  "H040M-": "USA-Stock",
  "H040M-EC": "USA-Stock",
  "H040M-ED": "USA-Stock",
  "H040M-EE": "USA-Stock",
  "H040M-EJ": "USA-Stock",
  "H040M-EM": "USA-Stock",
  "H040M-EN": "USA-Stock",
  "H040M-IP": "USA-Stock",
  "H040M-NH": "USA-Stock",
  "H040M-P2": "USA-Stock",
  "H040M-WH": "USA-Stock",
  "H494M-L5": "Global-EUROPE",
  "H494M-LQ": "Global-EUROPE",
  "H494M-LR": "Global-EUROPE",
  "H494M-LV": "Global-EUROPE",
  "H494M-LW": "Global-EUROPE",
  "H494M-LY": "Global-EUROPE",
  "H494M-LZ": "Global-EUROPE",
  "H718M-KL": "Global-Korea",
  "H718M-KM": "Global-Korea",
  "H718M-KS": "Global-Korea",
  "H718M-KX": "Global-Korea",
  "I201M-KO": "Global-Mexico",
  "I201M-MH": "Global-Mexico",
  "I201M-MK": "Global-Mexico",
  "I201M-MO": "Global-Mexico",
  "I201M-MV": "Global-Mexico",
  "I644M-IA": "Global-Panama",
  "I644M-NL": "Global-Panama",
  "I867M-XL": "Global-Chile",
  "I952M-O9": "Global-Peru",
  "J121M-JC": "USA-Stock",
  "K812M-KO": "USA-Stock",
  "K816M-1Z": "USA-Stock",
  "K816M-2Z": "USA-Stock",
  "K816M-3Z": "USA-Stock",
  "K816M-4Z": "USA-Stock",
  "K816M-EK": "USA-Stock",
  "K816M-H6": "USA-Stock",
  "K816M-Z5": "USA-Stock",
  "K816M-Z7": "USA-Stock",
  "L004M-2X": "Costco Australia",
  "S068M-EY": "USA-SAM'S",
  "S068M-EZ": "USA-SAM'S",
  "S068M-SM": "USA-SAM'S",
  "S068M-SQ": "USA-SAM'S",
  "S068M-SU": "USA-SAM'S",
  "S960M-F5": "Global-Malaysia",
  "S974M-SY": "Global-South Africa",
  "T059M-TZ": "USA-Target",
  "T082M-DE": "USA-Target",
  "T082M-DF": "USA-Target",
  "T082M-DH": "USA-Target",
  "T082M-DM": "USA-Target",
  "T082M-EI": "USA-Target",
  "T082M-EL": "USA-Target",
  "T082M-EO": "USA-Target",
  "T082M-FO": "USA-Target",
  "T082M-GA": "USA-Target",
  "T082M-GC": "USA-Target",
  "T082M-GD": "USA-Target",
  "T082M-GE": "USA-Target",
  "T082M-GF": "USA-Target",
  "W098M-0W": "USA-WALMART",
  "W098M-W1": "USA-WALMART",
  "W098M-W2": "USA-WALMART",
  "W098M-W3": "USA-WALMART",
  "W098M-WM": "USA-WALMART",
  "W098M-WQ": "USA-WALMART",
  "W098M-WR": "USA-WALMART",
  "W113M-HA": "USA-WALMART",
  "W113M-HC": "USA-WALMART",
  "W113M-HD": "USA-WALMART",
  "W113M-HE": "USA-WALMART",
  "W113M-HF": "USA-WALMART",
  "W113M-HH": "USA-WALMART",
  "W113M-HI": "USA-WALMART",
  "W113M-HJ": "USA-WALMART",
  "W113M-HK": "USA-WALMART",
  "W113M-HL": "USA-WALMART",
  "W113M-HN": "USA-WALMART",
  "W113M-HO": "USA-WALMART",
  "W113M-HP": "USA-WALMART",
  "W113M-HR": "USA-WALMART",
  "W846M-CN": "Global-Canada STOCK",
  "W846M-FZ": "Global-CANADA FGL SPORTS",
  "W846M-WN": "Global-CANADA WINNERS",
  "W847M-WO": "USA-WALMART",
  "Z090M-SV": "Global-Panama ZafariI",
};

export const SEASON: Record<string, string> = {
  s: "Spring",
  m: "Summer",
  f: "Fall",
  h: "Holiday",
};

export const SEASON_CODE: Record<string, number> = { s: 1, m: 2, f: 3, h: 4 };

export const EXCEL_COLUMN_HEADERS = [
  "Division",
  "Season",
  "Year",
  "Ref#",
  "Style",
  "Style Name",
  "Color",
  "Label",
  "Label Name",
  "Account",
  "Fashion Color",
  "Cost ($)",
  "Extension ($)",
  "PO#",
  "Terms Code",
  "DF/PO Placed",
  "Status",
  "Original ETD",
  "Ship Date",
  "Ship Month",
  "Days Late",
  "xFTY Date",
  "ETA Date",
  "Due Date",
  "PO Qty",
  "AIR/BOAT",
  "Freight Type",
  "Parent Vendor",
  "Contractor",
  "MSRP($)",
  "Brand(G1)",
  "Product(G2)",
  "Product Description",
  "SubBrand(G3)",
  "Size(G4)",
  "Size Range",
  "Size Configuration",
  "Pack Ratio",
  "Master Box Quantity",
  "Number Of Bundles",
  "Pieces In Bundle",
  "Hang/Flat",
  "Fashion Correctable Status",
  "Agent",
  "Country",
  "Season Code",
  "Gander",
  "LP",
  "ACC ShipDate",
  "Sum Ratio",
  "individual Polybag",
  "master Polybag",
  "Individual Polybag Quantity ",
  "Master Polybag Quantity ",
  "color Code",
  "RefCode",
  "Des Country",
  "2T",
  "3T",
  "4T",
  "4",
  "5",
  "6",
  "7",
  "6X",
  "7X",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "4/5",
  "6/7",
  "8",
  "10/12",
  "14/16",
  "18",
  "2A",
  "3A",
  "4A",
  "5A",
  "6A",
  "8A",
  "10A",
  "12A",
  "14A",
  "16A",
];

export const EXCEL_ROW_HEADERS = [
  "Division",
  "Season",
  "Year",
  "Ref#",
  "Style",
  "Style Name",
  "Color",
  "Label",
  "Label Name",
  "Account",
  "Fashion Color",
  "Cost ($)",
  "Extension ($)",
  "PO#",
  "Terms Code",
  "DF/PO Placed",
  "Status",
  "Original ETD",
  "Ship Date",
  "Ship Month",
  "Days Late",
  "xFTY Date",
  "ETA Date",
  "Due Date",
  "PO Qty",
  "AIR/BOAT",
  "Freight Type",
  "Parent Vendor",
  "Contractor",
  "MSRP($)",
  "Brand(G1)",
  "Product(G2)",
  "Product Description",
  "SubBrand(G3)",
  "Size(G4)",
  "Size Range",
  "Size Configuration",
  "Pack Ratio",
  "Master Box Quantity",
  "Number Of Bundles",
  "Pieces In Bundle",
  "Hang/Flat",
  "Fashion Correctable Status",
  "Agent",
  "Country",
  "Season Code",
  "Gander",
  "LP",
  "ACC ShipDate",
  "Sum Ratio",
  "individual Polybag",
  "master Polybag",
  "color Code",
  "RefCode",
  "Des Country",
  "Zode Code",
  "Size Group",
  "orderingNumber",
  "bySize",
  "REF-C-S-D",
  "finalQTY",
];

export const LABEL_ZODE_MAP: Record<string, string> = {
  "NO HANGER": "US",
  "WITH HANGER": "US",
  KOHLS: "US",
  "KOHLS.COM": "US",
  "KOHLS.COM - ALTERNATE": "US",
  "INDIVIDUAL POLYBAG": "US",
  ACADEMY: "AC",
  "WALMART STORES": "US",
  "WALMART STORES - ALTERNATE": "US",
  WALMART: "US",
  "WALMART - ALTERNATE": "US",
  "CANADA WORLD FAMOUS": "US",
  "TARGET.COM - ALTERNATE": "TA",
  "TARGET - ASSORTMENT": "TA",
  "ALTERNATE PACK": "US",
  "JC PENNEY": "US",
  "HBE EUROPE LEVIS": "EU",
  "INNOVA SPORT MEXICO": "MX",
  "INTERNATIONAL APPAREL CORP": "PA",
  "CENTRAL DEPARTMENT STORE LTD": "TH",
  "CHILE IAC": "CH",
  "AL-SRAD": "AS",
  DUBAI: "DU",
  "ZAFARI PANAMA": "PZ",
  "KOREA ALT PACKING": "KO",
  SKYE: "SA",
  "INDIA APPAREL GROUP": "IN",
  "CANADA - WINNERS": "CA",
  "PERU IAC": "PE",
  "CANADA - STOCK": "CA",
  "STREAM MALAYSIA": "ML",
  "HADDAD CANADA": "US-CA",
  "CANADA - WALMART STORE": "CA",
};

export const POLY_BAG: Record<
  string,
  { individual: boolean; master: boolean }
> = {
  "AL-SRAD": { individual: true, master: true },
  "CENTRAL DEPARTMENT STORE LTD": { individual: true, master: false },
  "CHILE IAC": { individual: false, master: true },
  DUBAI: { individual: true, master: false },
  "INDIVIDUAL POLYBAG": { individual: true, master: false },
  "INNOVA SPORT MEXICO": { individual: true, master: true },
  "INTERNATIONAL APPAREL CORP": { individual: false, master: true },
  KOHLS: { individual: false, master: true },
  "KOHLS.COM": { individual: true, master: false },
  "KOHLS.COM - ALTERNATE": { individual: true, master: false },
  "KOREA ALT PACKING": { individual: true, master: false },
  "PERU IAC": { individual: false, master: true },
  SKYE: { individual: true, master: true },
  "STREAM MALAYSIA": { individual: true, master: true },
  WALMART: { individual: true, master: false },
  "WALMART - ALTERNATE": { individual: true, master: false },
  "ZAFARI PANAMA": { individual: true, master: true },
  "JC PENNEY": { individual: false, master: true },
  "DICK'S SPORTING GOODS": { individual: false, master: true },
  DEFAULT: { individual: false, master: false },
};

export const SIZE_GROUP: Record<string, string> = {
  "H040M-2T": "TODDLER",
  "H040M-3T": "TODDLER",
  "H040M-4T": "TODDLER",
  "H040M-4": "BOYS 4-7X",
  "H040M-5": "BOYS 4-7X",
  "H040M-6": "BOYS 4-7X",
  "H040M-7": "BOYS 4-7X",
  "K812M-4": "BOYS 4-7X",
  "K812M-5": "BOYS 4-7X",
  "K812M-6": "BOYS 4-7X",
  "K812M-7": "BOYS 4-7X",
  "H040M-L": "BIG BOYS ALPHA (XS - XL)",
  "H040M-M": "BIG BOYS ALPHA (XS - XL)",
  "H040M-S": "BIG BOYS ALPHA (XS - XL)",
  "H040M-XL": "BIG BOYS ALPHA (XS - XL)",
  "K812M-S": "BIG BOYS ALPHA (XS - XL)",
  "K812M-M": "BIG BOYS ALPHA (XS - XL)",
  "K812M-L": "BIG BOYS ALPHA (XS - XL)",
  "K812M-XL": "BIG BOYS ALPHA (XS - XL)",
  "A109M-S": "BIG BOYS ALPHA (XS - XL)",
  "A109M-M": "BIG BOYS ALPHA (XS - XL)",
  "A109M-L": "BIG BOYS ALPHA (XS - XL)",
  "A109M-XL": "BIG BOYS ALPHA (XS - XL)",
  "K816M-S": "BIG BOYS ALPHA (XS - XL)",
  "K816M-M": "BIG BOYS ALPHA (XS - XL)",
  "K816M-L": "BIG BOYS ALPHA (XS - XL)",
  "K816M-XL": "BIG BOYS ALPHA (XS - XL)",
  "A062M-4": "BOYS 4-7X",
  "A062M-5": "BOYS 4-7X",
  "A062M-6": "BOYS 4-7X",
  "A062M-7": "BOYS 4-7X",
  "A062M-S": "BIG BOYS ALPHA (XS - XL)",
  "A062M-M": "BIG BOYS ALPHA (XS - XL)",
  "A062M-L": "BIG BOYS ALPHA (XS - XL)",
  "A062M-XL": "BIG BOYS ALPHA (XS - XL)",
  "J376M-4": "BOYS 4-7X",
  "J376M-5": "BOYS 4-7X",
  "J376M-6": "BOYS 4-7X",
  "J376M-7": "BOYS 4-7X",
  "J376M-S": "BIG BOYS ALPHA (XS - XL)",
  "J376M-M": "BIG BOYS ALPHA (XS - XL)",
  "J376M-L": "BIG BOYS ALPHA (XS - XL)",
  "J376M-XL": "BIG BOYS ALPHA (XS - XL)",
  "J372M-4": "BOYS 4-7X",
  "J372M-5": "BOYS 4-7X",
  "J372M-6": "BOYS 4-7X",
  "J372M-7": "BOYS 4-7X",
  "J372M-S": "BIG BOYS ALPHA (XS - XL)",
  "J372M-M": "BIG BOYS ALPHA (XS - XL)",
  "J372M-L": "BIG BOYS ALPHA (XS - XL)",
  "J372M-XL": "BIG BOYS ALPHA (XS - XL)",
};
